import { Bot, BrainCircuit, Download, Radar, Route, ShieldAlert, Waves } from "lucide-react";
import { PageIntro } from "../../components/ui/page-intro";
import {
  LoadingSkeleton,
  SectionCard,
  StatusBadge,
} from "../../components/ui/enterprise-widgets";
import {
  useAgentStatus,
  useCityBrainBriefing,
  useDigitalTwinOverview,
  useIncidents,
  useReportsCatalog,
} from "../enterprise/use-enterprise-operations";
import { usePlatform } from "../platform/platform-context";

export function CityBrainPage(): JSX.Element {
  const { data: briefing, isLoading: isBriefingLoading } = useCityBrainBriefing();
  const { data: agents, isLoading: isAgentsLoading } = useAgentStatus();
  const { data: twin, isLoading: isTwinLoading } = useDigitalTwinOverview();
  const { data: incidents, isLoading: isIncidentsLoading } = useIncidents();
  const { data: reports } = useReportsCatalog();
  const { triggerQuickAction } = usePlatform();

  return (
    <section className="space-y-6">
      <PageIntro
        eyebrow="Multi-Agent Reasoning"
        title="City Brain autonomous command center"
        summary="Cross-domain reasoning, digital twin intelligence, incident correlation, predictive recommendations, and enterprise workflow orchestration."
      />

      <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
        <SectionCard
          title="Executive Briefing"
          description="Autonomous cross-domain reasoning with explainable recommendations"
          action={<StatusBadge label={briefing ? `Risk ${briefing.risk_score}` : "Loading"} tone="warning" pulse />}
        >
          {isBriefingLoading || !briefing ? (
            <LoadingSkeleton rows={4} />
          ) : (
            <div className="space-y-4">
              <div className="rounded-[24px] border border-accent-400/20 bg-accent-500/10 p-5">
                <p className="text-sm font-semibold text-primary">{briefing.headline}</p>
                <p className="mt-3 text-sm leading-6 text-muted">{briefing.executive_summary}</p>
                <div className="mt-4 flex flex-wrap gap-2">
                  <StatusBadge
                    label={`Confidence ${(briefing.confidence_score * 100).toFixed(0)}%`}
                    tone="success"
                  />
                  <StatusBadge label={`${briefing.predicted_window_minutes} minute window`} tone="accent" />
                </div>
              </div>
              <div className="grid gap-4 md:grid-cols-2">
                <div className="rounded-2xl border border-white/8 bg-white/5 p-4">
                  <p className="text-sm font-medium text-primary">Recommendations</p>
                  <div className="mt-3 space-y-2">
                    {briefing.recommendations.map((item) => (
                      <div key={item} className="rounded-xl border border-white/8 bg-surface-900/50 p-3 text-sm text-muted">
                        {item}
                      </div>
                    ))}
                  </div>
                </div>
                <div className="rounded-2xl border border-white/8 bg-white/5 p-4">
                  <p className="text-sm font-medium text-primary">Reasoning Chain</p>
                  <div className="mt-3 space-y-2">
                    {briefing.reasoning.map((item) => (
                      <div key={item} className="rounded-xl border border-white/8 bg-surface-900/50 p-3 text-sm text-muted">
                        {item}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          )}
        </SectionCard>

        <SectionCard
          title="Autonomous Workflows"
          description="Production-ready action packages generated by City Brain"
          action={<StatusBadge label="Workflow engine" tone="success" />}
        >
          {isBriefingLoading || !briefing ? (
            <LoadingSkeleton rows={3} />
          ) : (
            <div className="space-y-3">
              {briefing.autonomous_workflows.map((workflow) => (
                <button
                  key={workflow}
                  className="flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white/5 px-4 py-4 text-left text-sm text-primary transition hover:border-accent-400/30 hover:bg-accent-500/10"
                  onClick={() => triggerQuickAction(`Launch ${workflow}`)}
                  type="button"
                >
                  <span>{workflow}</span>
                  <Bot className="h-4 w-4 text-accent-300" />
                </button>
              ))}
              {reports?.map((report) => (
                <button
                  key={report.id}
                  className="flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white/5 px-4 py-4 text-left text-sm text-primary transition hover:border-accent-400/30 hover:bg-accent-500/10"
                  onClick={() => triggerQuickAction(`Export ${report.title}`)}
                  type="button"
                >
                  <span>{report.title}</span>
                  <Download className="h-4 w-4 text-muted" />
                </button>
              ))}
            </div>
          )}
        </SectionCard>
      </div>

      <div className="grid gap-6 xl:grid-cols-[0.95fr_1.05fr]">
        <SectionCard
          title="Specialized AI Agents"
          description="Domain agents monitor, explain, escalate, and coordinate through City Brain"
          action={<StatusBadge label="12-agent fabric" tone="accent" pulse />}
        >
          {isAgentsLoading || !agents ? (
            <LoadingSkeleton rows={4} />
          ) : (
            <div className="space-y-3">
              {agents.map((agent) => (
                <div key={agent.name} className="rounded-2xl border border-white/8 bg-white/5 p-4">
                  <div className="flex flex-wrap items-center justify-between gap-3">
                    <div>
                      <p className="text-sm font-medium text-primary">{agent.name}</p>
                      <p className="mt-2 text-sm leading-6 text-muted">{agent.anomaly}</p>
                    </div>
                    <StatusBadge
                      label={`${(agent.confidence_score * 100).toFixed(0)}% confidence`}
                      tone={agent.severity === "critical" ? "danger" : agent.severity === "high" ? "warning" : "success"}
                    />
                  </div>
                  <div className="mt-3 grid gap-3 md:grid-cols-2">
                    <div className="rounded-xl border border-white/8 bg-surface-900/50 p-3 text-sm text-muted">
                      {agent.recommendation.summary}
                    </div>
                    <div className="rounded-xl border border-white/8 bg-surface-900/50 p-3 text-sm text-muted">
                      {agent.recommendation.rationale}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </SectionCard>

        <SectionCard
          title="Digital Twin and Incident Correlation"
          description="Live operational twin, failures, simulations, and incident workflow state"
          action={<StatusBadge label="Replay enabled" tone="success" />}
        >
          {isTwinLoading || isIncidentsLoading || !twin || !incidents ? (
            <LoadingSkeleton rows={5} />
          ) : (
            <div className="space-y-4">
              <div className="grid gap-3 md:grid-cols-2">
                {[
                  { icon: <Radar className="h-4 w-4" />, label: "Twin Layers", value: `${twin.layers.length}` },
                  { icon: <ShieldAlert className="h-4 w-4" />, label: "Active Failures", value: `${twin.active_failures.length}` },
                  { icon: <Route className="h-4 w-4" />, label: "Incidents", value: `${incidents.length}` },
                  { icon: <Waves className="h-4 w-4" />, label: "Simulations", value: `${twin.simulations.length}` },
                ].map((item) => (
                  <div key={item.label} className="rounded-2xl border border-white/8 bg-white/5 p-4">
                    <div className="flex items-center gap-3 text-primary">
                      {item.icon}
                      <p className="text-sm font-medium">{item.label}</p>
                    </div>
                    <p className="mt-3 text-2xl font-semibold text-primary">{item.value}</p>
                  </div>
                ))}
              </div>
              <div className="space-y-3">
                {twin.simulations.map((scenario) => (
                  <div key={scenario.name} className="rounded-2xl border border-white/8 bg-white/5 p-4">
                    <div className="flex items-center justify-between gap-3">
                      <p className="text-sm font-medium text-primary">{scenario.name}</p>
                      <StatusBadge
                        label={`${(scenario.confidence_score * 100).toFixed(0)}%`}
                        tone="accent"
                      />
                    </div>
                    <p className="mt-2 text-sm leading-6 text-muted">{scenario.impact}</p>
                  </div>
                ))}
                {incidents.map((incident) => (
                  <div key={incident.id} className="rounded-2xl border border-white/8 bg-white/5 p-4">
                    <div className="flex items-center justify-between gap-3">
                      <p className="text-sm font-medium text-primary">{incident.title}</p>
                      <StatusBadge
                        label={incident.status}
                        tone={incident.priority === "Critical" ? "danger" : "warning"}
                      />
                    </div>
                    <p className="mt-2 text-sm text-muted">
                      {incident.location} • {incident.owner}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </SectionCard>
      </div>
    </section>
  );
}
